# Generated by Django 3.0.5 on 2021-04-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='image',
            field=models.CharField(choices=[('white-sofa.jpg', 'white-sofa.jpg'), ('kitchen-table.jpg', 'kitchen-table.jpg'), ('king-bed.jpg', 'king-bed.jpg'), ('toaster.jpg', 'toaster.jpg'), ('wooden-chair.jpg', 'wooden-chair.jpg')], max_length=255, null=True),
        ),
    ]
