# Generated by Django 3.0.5 on 2021-04-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_furniture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
